# Generated by Django 2.1.5 on 2019-02-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='computing_id',
            field=models.CharField(default='none', max_length=6),
            preserve_default=False,
        ),
    ]
