# Generated by Django 2.1.5 on 2019-03-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0004_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
