# Generated by Django 2.1.5 on 2019-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0006_auto_20190315_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='default-user.jpg', upload_to='images/'),
        ),
    ]
