# Generated by Django 2.1.5 on 2019-03-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0007_student_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='friends',
            field=models.ManyToManyField(blank=True, to='skillMatch.Student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='media/default-user.jpg', upload_to='images/'),
        ),
    ]
