# Generated by Django 2.1.5 on 2019-04-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0008_auto_20190331_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='static/default-user.jpg', upload_to=''),
        ),
    ]
