# Generated by Django 2.1.5 on 2019-04-01 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0010_auto_20190331_2337'),
        ('skillMatch', '0015_auto_20190401_0055'),
    ]

    operations = [
    ]
