# Generated by Django 2.1.5 on 2019-04-01 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0016_merge_20190401_2009'),
        ('skillMatch', '0008_auto_20190325_1804'),
    ]

    operations = [
    ]
