# Generated by Django 2.1.5 on 2019-04-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0017_merge_20190401_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(default='static/default-user.jpg', upload_to='images/'),
        ),
    ]
