# Generated by Django 2.1.5 on 2019-04-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0018_auto_20190401_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='semester',
            field=models.CharField(max_length=3),
        ),
    ]
