# Generated by Django 2.1.5 on 2019-04-27 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skillMatch', '0019_auto_20190426_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skillMatch.Student')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skillMatch.Post')),
            ],
        ),
    ]
